#ifndef __client_main_frame__
#define __client_main_frame__

/**
@file
Subclass of ClientMainFrameBase, which is generated by wxFormBuilder.
*/

#include "wxFormBuilder/gui_widgets_base.h"

//// end generated include

namespace rco {

/** Implementing ClientMainFrameBase */
class ClientMainFrame : public ClientMainFrameBase {
 protected:
  // Handlers for ClientMainFrameBase events.
  void m_textCtrlKeyInOnTextEnter(wxCommandEvent& event) override;

  void receiveThreadEventHandler(wxThreadEvent& event);

 public:
  /** Constructor */
  explicit ClientMainFrame(wxWindow* parent);
  //// end generated class members

  virtual ~ClientMainFrame();
};

}  // end of namespace rco

#endif  // __client_main_frame__
